[supabase]
url = "https://fiiknmmafjyhbdfrnnhh.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpaWtubW1hZmp5aGJkZnJubmhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDk1MTI1NCwiZXhwIjoyMDkwNTI3MjU0fQ.CT5fwxSYVMxpl4AiZMqYsPQx-zW-P9luAocuQBEgKko"
